### PR TITLE
[EXE-2060] Add aiq_week_diff pushdown

### PR DESCRIPTION
**Pull request by dorisZ017**
https://github.com/ActionIQ/flame/pull/572

### CODE REVIEW

**Comment by yannistze** [comment]
Same comments as https://github.com/ActionIQ/flame/pull/572 👍
Let me know when you need me to take another look 👍

**Comment by dorisZ017** [comment]
> Same comments as [ActionIQ/flame#572](https://github.com/ActionIQ/flame/pull/572) 👍 Let me know when you need me to take another look 👍

@yannistze Done, let me know what you think

**Review by yannistze — APPROVED** [review]
LGTM 👍

**Comment by dorisZ017** [comment]
> published spark-redshift_2.12 to https://actioniq.jfrog.io/artifactory/aiq-sbt-local/io/github/spark-redshift-community/spark-redshift_2.12/5.1.0-aiq10/spark-redshift_2.12-5.1.0-aiq10.jar

**Pull request merged**
